MENU = {
    1: {"name": "Cesario pizza", "time": 35},
    2: {"name": "Margarita pizza", "time": 25},
    3: {"name": "Pepperoni pizza", "time": 25},
    4: {"name": "Napoli pizza", "time": 30},
    5: {"name": "Quattro Formaggi pizza", "time": 35},
    6: {"name": "Capricciosa pizza", "time": 30},
    7: {"name": "Hawaii pizza", "time": 30},
    8: {"name": "Carbonara pizza", "time": 30},
    9: {"name": "Parma pizza", "time": 30},
    10: {"name": "American breakfast", "time": 30},
    11: {"name": "Avocado toast with shrimp", "time": 15},
    12: {"name": "Croissant with salmon", "time": 25},
    13: {"name": "Croissant with chicken", "time": 25},
    14: {"name": "Scramble with guacamole", "time": 15},
    15: {"name": "Quinoa bowl", "time": 25},
    16: {"name": "Pancakes with seasonal fruits", "time": 20},
    17: {"name": "Sandwich with ham", "time": 15},
    18: {"name": "Sandwich with chicken", "time": 15},
    19: {"name": "Sandwich with tuna", "time": 15},
    20: {"name": "Frittata with vegetables", "time": 35},
    21: {"name": "Syrnyky", "time": 10},
    22: {"name": "Espresso", "time": 10},
    23: {"name": "Americano", "time": 10},
    24: {"name": "Cappuccino", "time": 10},
    25: {"name": "Latte", "time": 10},
    26: {"name": "Nuggets", "time": 15},
    27: {"name": "Cheese Brie fries with raspberry sauce", "time": 15},
    28: {"name": "French fries", "time": 25},
    29: {"name": "Cheese balls with raspberry sauce", "time": 15},
    30: {"name": "Ketchup", "time": 3},
    31: {"name": "Burger sauce", "time": 3},
    32: {"name": "Cheese cheddar sause", "time": 5},
    33: {"name": "Caesar sauce", "time": 3},
    34: {"name": "Barbecue sauce", "time": 3},
    35: {"name": "Tartar sauce", "time": 3},
    36: {"name": "Raspberry sauce", "time": 3},
    37: {"name": "Espresso", "time": 10},
    38: {"name": "Americano", "time": 10},
    39: {"name": "Americano with milk", "time": 10},
    40: {"name": "Caesario salad with chicken", "time": 25},
    41: {"name": "Caesario salad with salmon", "time": 25},
    42: {"name": "Rivera salad", "time": 15},
    43: {"name": "Di Prosciutto salad", "time": 25},
    44: {"name": "Borscht", "time": 35},
    45: {"name": "Chicken broth", "time": 25},
    46: {"name": "Cheese cream soup", "time": 15},
    47: {"name": "Rye bread", "time": 5},
    48: {"name": "Wheat bread", "time": 5},
    49: {"name": "Salad with chicken and pineapple", "time": 15},
    50: {"name": "Rice with turkey", "time": 25},
    51: {"name": "Fried potatoes with mushrooms and cheddar cheese", "time": 20},
    52: {"name": "Mashed potatoes", "time": 15},
    53: {"name": "Asian-style vegetables", "time": 20},
    54: {"name": "Carbonara", "time": 25},
    55: {"name": "Marinara pasta with stracchatella", "time": 25},
    56: {"name": "Pasta with tuna", "time": 25},
    57: {"name": "Basque cheesecake", "time": 25},
    58: {"name": "Cherry tart", "time": 15},
    59: {"name": "Apple tart", "time": 15},
    60: {"name": "Andrut", "time": 20},
    61: {"name": "Cinnabon Pistachio-raspberry", "time": 25},
    62: {"name": "Chocolate cinnabon", "time": 25},
    63: {"name": "Cinnabon with cherries", "time": 25},
    64: {"name": "Cinnabon with caramel", "time": 25},
    65: {"name": "Mojito", "time": 5},
    66: {"name": "Lemonade classic", "time": 5},
    67: {"name": "Compote", "time": 5},
    68: {"name": "Coke", "time": 5},
    69: {"name": "Water", "time": 5},
    61: {"name": "Apple juice", "time": 5},
    62: {"name": "Grape juice", "time": 5},
    63: {"name": "Orange juice", "time": 1},
    64: {"name": "Pineapple juice", "time": 5},
    65: {"name": "White wine", "time": 5},
    66: {"name": "White sparkling wine", "time": 5},
    67: {"name": "Red wine", "time": 5},
    68: {"name": "Beer", "time": 5},
    69: {"name": "Whiskey", "time": 5},
    70: {"name": "Liquor", "time": 5},
}

